# Use the official Node.js image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy only the necessary directories
COPY pages ./pages
COPY pages/api ./pages/api
COPY pages/components ./pages/components
COPY styles ./styles

# Expose port
EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev"]
