# Use the official Node.js image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy only the necessary directories
COPY server ./server

# Expose port
EXPOSE 3001

# Start the backend server
CMD ["node", "server/server.js"]
